version: '3'
services:
  web:
    image: nginx:stable
    depends_on:
      - php
    ports:
      - '8080:80'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./html:/var/www/html
  php:
    image: php:7-fpm
    volumes:
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./html:/var/www/html